### ISSUE TITLE
Question - File copy support in io/nio module

### ISSUE THREAD

**Issue by PerfectSlayer** [topjohnwu/libsu#122]
Hi,

I would like to know if there is any plan to support Java NIO feature like [Files.copy](https://docs.oracle.com/javase/8/docs/api/java/nio/file/Files.html#copy-java.nio.file.Path-java.nio.file.Path-java.nio.file.CopyOption...-) API to copy file efficiently without having to use old Input/OutputStreams (to prevent the os > vm > bytes > vm > os path).

Right now, I am still using `dd if=... of=...` in a root shell to copy files.
I just would like to know if there is anything present or planned to cover this use case.
If not, anything in mind that would do the job? I could do a PR to contribute a such feature if you are interested.

Regards

**Comment by topjohnwu** [comment]
Sure, I'll add this onto the list of things to implement!

**Comment by PerfectSlayer** [comment]
Oh, I didn't want the issue turns into a feature request but thank you!
If you need help, let me know.

_(you can close the issue if you want as my question was answered)_

**Comment by topjohnwu** [comment]
Actually, after thinking about it a little more, these kind of API doesn't seem necessary: you can just simply call `Files.copy` directly in a root service. The `nio` and `io` modules are designed to bridge the remote process with the non-root process, for instance: reading and process files (in the non-root process!) that are usually unaccessible.

For instance: the Magisk app requires reading directly from the boot partition, process the boot image, and then dump the boot image back to the block device. Since the processing logic is extremely complex and is tightly coupled with the UI, it does not make sense to put the entire installation operation into the root service.

For your use case in particular, it doesn't seem like you need to cross the IPC boundary. So doing a direct copy in the root service seems to be what you want to do. Using `dd` is actually not too bad either, although the performance will be much worse, and the `dd` command on old Android is... weird (I usually use `cat in > out` instead for portability).

For the performance comparison: using root service only requires 1 Binder transaction + the actual I/O; using shell command with `dd` or `cat` will have to spawn 2 additional threads to gobble stdout/err, multiple I/O operations on stdin/out/err, spawn a new process to run the tool, then finally, the actual I/O.

**Comment by topjohnwu** [comment]
Doing things in a root service also have some bonus! You can directly open a `FileChannel`, and its `transferTo` method will actually perform zero copies in its native implementation. Or you can manually poke into `Os` and call the raw `sendfile` system call :D

**Comment by gudenau** [comment]
It would be nice to be able to use the standard NIO Path and File methods to access remote files.

Stuff like
```Java
var path = remote.getPath("/some/path");
try(var stream = Files.list(path)) {
    stream.filter(Files::isRegularFile)
        .forEach((file) -> {
            try(var reader = Files.newBufferedReader(file)) {
                reader.lines().forEach(System.out::println);
            } catch(IOException e) {
                //...
            }
        });
}
```
as a quick and dirty example.
