### ISSUE TITLE
Request: have a fork that calls the commands via Shizuku 

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [topjohnwu/libsu#127]
I was told that Shizuku can be used to execute su commands even on a non-rooted device.

I'm talking about this :
https://github.com/RikkaApps/Shizuku-API
https://github.com/RikkaApps/Shizuku

Can you please create a new repository which behaves as similar as the current one, yet uses Shizuku instead?
Or add the functions here, if you think it's a good thing to have here... 
:)

This way, apps that rely on libsu could easily also add support for non-rooted devices that use Shizuku.

**Comment by KieronQuinn** [comment]
> I was told that Shizuku can be used to execute su commands even on a non-rooted device.

You were told wrong.

Shizuku runs as `shell`, which has some privileges -  specifically [these](https://cs.android.com/android/platform/superproject/+/master:frameworks/base/packages/Shell/AndroidManifest.xml) permissions, as well as some special cases in some system services when you call them with the `shell` UID (`2000`). It does **not** allow you to run commands as root on an unrooted device.

What you are probably looking for is [Rish](https://github.com/RikkaApps/Shizuku-API/blob/master/rish/README.md), which is the closest thing to `su` for running arbitrary commands as shell. But, again, it does not allow you to run everything because `shell` != `root`.

Meanwhile, the closest thing to libsu's RootService, is well, Shizuku API. Their functionality is fairly close, although libsu doesn't have a built in close callback (that I know of anyway). You can see an example of an app that is able to use either with my own [DarQ](https://github.com/KieronQuinn/DarQ).

Side note: Shizuku also will run Shizuku API services as `root` if it's started as root, from a rooted device. You can also use its sibling, [Sui](https://github.com/RikkaApps/Sui), which uses the same API and always runs as root.

**Comment by AndroidDeveloperLB** [comment]
Wait now I'm very confused. I was talking about Shizuku-API. 
Can't it be used to perform all su operations? Look what I was told:
https://github.com/RikkaApps/Shizuku/issues/229#issuecomment-1179686721

> shizuku is lower level than the su or adb commands. If you like, you can implement the commands you need yourself.

Also:
Question: "Does Shizuku support replacement of "su" commands, so that you could run them on a non-rooted device?"
Answer: "Of course, you can implement something like "su" , but you need to some more codes."

I was also told to do it for the "Runtime.exec".
And the issue was closed even though I still believe it can't do it, and wanted them to show more explanation.

So is there any library that will allow to perform operations that were possible only on a rooted device, yet on a non-rooted device?
For example copying files from a protected folder, or even get the list of files of a protected folder?

**Comment by KieronQuinn** [comment]
Let's start with your example:

> copying files from a protected folder, or even get the list of files of a protected folder?

Depends on the folder. There are a few that are write-accessible to Shell that aren't to normal users, for example `/data/local/tmp` and `/sdcard/Android/data`, but if you're looking to read from or write to say `/data/data`, Shizuku is **not** sufficient.

My recommendation in general would be:

If you're looking to use something specific with `Runtime.exec()` as Shell, use Shizuku API via a binder (UserService as Rikka suggested). This will allow you to run commands as shell, you could even pass an argument to the bound service with your command. But the whole point of Shizuku's API is that running commands and parsing the output is very slow and error-prone, so for your example of listing files, you can just use the regular Java File API from within the Shizuku-bound service. I see you're also asking about chmod and the like, and as Rikka said there's proper Java calls to do that rather than having to use commands.

Like I said though, there is [Rish](https://github.com/RikkaApps/Shizuku-API/blob/master/rish/README.md), which if it were in the PATH could be used by `Runtime.exec()` in the same way that many apps before libsu and equivalents came along did `su -c <command>` from within `Runtime.exec()`

One thing is for certain though: This isn't something that would be in scope for libsu, I guarantee it.

**Comment by AndroidDeveloperLB** [comment]
I mean all folders that I can reach via a rooted device. This included files of other apps (of /data/data/...).
I don't understand how to do it for Runtime.exec() because it's not a service. It's a singleton class that you need to reach via a static function (getRuntime). 
I don't understand what Rish is. You mean it's for commands like "cp ..." , "chmod ..."  ?

It's a yes/no question, which I asked them (and they said yes):
Can Shizuku-API (or anything else) be a complete replacement of having a rooted device and using su commands on it?

If I want to copy files from /data/data/some_other_app_package_name , will it let me do it even on a non-rooted device?

**Comment by KieronQuinn** [comment]
Look, there's a really easy way to show you which folders you can access.

Open `adb shell`. Try to `cd` into an app's data. For example `cd /data/data/com.google.android.apps.nexuslauncher`. 

You will get permission denied. You can only get into an app's data if it's debuggable and you use `run-as`. 

ADB shell is running as `shell`, the same as Shizuku, unless - like I said - it's been started as root, in which case it's the same as running through libsu. **But that is only the case on a rooted device.**

Your intention appears to be accessing app data of other production apps. **You cannot do this with Shizuku alone**. There's limited app data access with `adb backup` and `adb restore` that could probably be used via Shizuku API, but that's limited to apps that allow it. 

Again, this is most definitely not something that is in scope for libsu.

**Comment by AndroidDeveloperLB** [comment]
@KieronQuinn See this is another thing that I find weird there as it's not documented: The docs mention "bindUserService", so this means I can write whatever I wish into the UserService class, and it will run on the process that Shizuru created, supposedly as a root device?
If so, this is quite a general solution, no? I could just have there the call to the shell commands, no? And for specific cases that there is an API, I could use it instead.

Thing is, still, as my original question: I don't think it will let me reach the protected files.

I've tried now to add this to the class "UserService" :

```
    @Override
    public String doSomething() throws RemoteException {
        final File protectedFolder = new File("/data/data/com.android.vending");
        final String[] innerFiles = protectedFolder.list();
        int childCount = innerFiles == null ? 0 : innerFiles.length;
        String message="protectedFolder:" + protectedFolder + " exists?" + protectedFolder.exists() + " readable?" + protectedFolder.canRead() + " childCount:" + childCount;
        return message;
    }
```

And indeed it shows it can't reach it

**Comment by KieronQuinn** [comment]
It's used in the demo, as the guide says: https://github.com/RikkaApps/Shizuku-API/blob/28c6d65ff47f66277422019e87fa56c85e326f78/demo/src/main/java/rikka/shizuku/demo/DemoActivity.java

But I can tell you from the off that that will not work. Shell does not have access to that directory.

**Comment by RikkaW** [comment]
You keep asking if Shizuku can be used like "su", our understanding is you are too lazy to read the document and write new codes, but your real problem is if Shizuku can elevate the privilege from adb to root. The answer is no, of course. We all take this and what adb can do as basic knowledge.
