### ISSUE TITLE
Implicit Dependencies

### ISSUE THREAD

**Issue by gurupras** [topjohnwu/libsu#13]
This is more of a question than an issue.

I'd like to use this library, but before I do so, I'd like to know if this library has any implicit dependendies. For example, does the library depend on Magisk being used? Will it work with ChainfireSU or any other traditional `su` setup?

**Comment by gurupras** [comment]
I'm writing a simple Android app that has certain features that requires root support. I'd like to use library as part of my app to help setup and run the root commands. I just wanted to know if it somehow depended on a specific su implementation (Magisk/Chainfire/etc)

**Comment by topjohnwu** [comment]
Just like @PerfectSlayer said, the library will call `su`, and should support any possible root, including MagiskSU, SuperSU, KingRoot, CM Superuser, phhsu, super old ChainsDD Superuser etc.
The mount master option (you can enable it with a flag) will call `su --mount-master`, which I know MagiskSU and SuperSU both supports. Not sure with other root solutions since I've never used them before.

For the library itself, the dependency that will end up in the package you receive (and then later contain in your app) is the [Android Support Annotations](https://developer.android.com/reference/android/support/annotation/package-summary) library, part of Google's open source support library. Retrolambda is to transform the final bytecode from Java 8 to Java 7 so my released library `aar` will be compatible with projects not using the latest gradle plugin to desugar Java 8 bytecode, none of its code will be added to the project.

`libsu`'s API will very soon go to 2.0, which is drastically different from 1.X.X versions. You can preview it on the `2.0` branch.
