### ISSUE TITLE
Service connect from\to RootService

### ISSUE THREAD

**Issue by turqcacke** [topjohnwu/libsu#130]
I'm getting and parsing information in root service, so to safe it in comfortable format instead of using self-written parsers from Shell output. I want to another (concrete) app also could get it by connecting to my root service.
 
**1. Is it possible to connect to RootService like a normal android service by intent and action or any way to do it?**

So if it's not possible to connect the second option which i have to send the data when it's needed, by connecting to my app. But while connecting from RootService  got this

`java.lang.SecurityException: Unable to find app for caller android.app.IApplicationThread$Stub$Proxy@1435f7f (pid=5607) when binding service Intent { act=com.demo.reader.PREF_RW cmp=com.demo.reader/.ReadWriteSharedService }`

**2. Is there any way to connect to another app from root service ?**

**Comment by topjohnwu** [comment]
It is a little out of scope for this project so I'll close this issue, but I'll provide you some advice/starters.

It is not possible to send broadcasts or intents directly within the root service to another process since activity manager is not managing the root process. However, you can send the remote binder proxy you received in your app's non-root process to another app's non-root process through intents/bundle/content provider etc. So the basic idea is that you pick your preferred way to send over the `IBinder` object received in your `ServiceConnection` callback using official Android inter-package communication methods.

**Comment by turqcacke** [comment]
> It is a little out of scope for this project so I'll close this issue, but I'll provide you some advice/starters.
> 
> It is not possible to send broadcasts or intents directly within the root service to another process since activity manager is not managing the root process. However, you can send the remote binder proxy you received in your app's non-root process to another app's non-root process through intents/bundle/content provider etc. So the basic idea is that you pick your preferred way to send over the `IBinder` object received in your `ServiceConnection` callback using official Android inter-package communication methods.

If I understand right, the idea is to take `IBinder` which getting in `onServiceConnected` object to put in Bundle/intent extars and then it would be possible to use it in scope of another process, so than I would like to clarify one thing. When `IBinder` received to write it into bundle/intent extras it should be parsed to bytes and than parsed back to object to use it. Did I got your approach, if not please correct me?
